export const KPIMock = {
  dayRemaining: '18',
  surveys: { count: '692', goal: '2000' },
  calls: { count: '784', toRemind: '78' },
  averageTime: '7 min 13',
}

export const callingMock = [
  { type: 'calling', firstName: 'Maria', lastName: 'Curtis', count: 692, totalCount: 2000 },
  { type: 'calling', firstName: 'Aspen', lastName: 'Calzoni', count: 92, totalCount: 150 },
  { type: 'calling', firstName: 'Cristofer', lastName: 'Lipshutz', count: 475, totalCount: 500 },
  { type: 'calling', firstName: 'Davis', lastName: 'Vetrovs', count: 4350, totalCount: 20593 },
  { type: 'calling', firstName: 'Maria', lastName: 'Curtis', count: 5578, totalCount: 10000 },
  { type: 'calling', firstName: 'Aspen', lastName: 'Calzoni', count: 32, totalCount: 100 },
  { type: 'calling', firstName: 'Cristofer', lastName: 'Lipshutz', count: 32, totalCount: 1500 },
  { type: 'calling', firstName: 'Davis', lastName: 'Vetrovs', count: 0, totalCount: 700 },
  { type: 'calling', firstName: 'Maria', lastName: 'Curtis', count: 145, totalCount: 500 },
  { type: 'calling', firstName: 'Aspen', lastName: 'Calzoni', count: 32, totalCount: 50 },
  { type: 'calling', firstName: 'Cristofer', lastName: 'Lipshutz', count: 92, totalCount: 100 },
  { type: 'calling', firstName: 'Davis', lastName: 'Vetrovs', count: 0, totalCount: 100 },
  { type: 'calling', firstName: 'Maria', lastName: 'Curtis', count: 6, totalCount: 100 },
  { type: 'calling', firstName: 'Aspen', lastName: 'Calzoni', count: 61989, totalCount: 78990 },
  { type: 'calling', firstName: 'Cristofer', lastName: 'Lipshutz', count: 32, totalCount: 100 },
  { type: 'calling', firstName: 'Davis', lastName: 'Vetrovs', count: 0, totalCount: 1000 },
  { type: 'calling', firstName: 'Maria', lastName: 'Curtis', count: 245, totalCount: 300 },
  { type: 'calling', firstName: 'Aspen', lastName: 'Calzoni', count: 56, totalCount: 100 },
  { type: 'calling', firstName: 'Cristofer', lastName: 'Lipshutz', count: 320, totalCount: 1000 },
  { type: 'calling', firstName: 'Davis', lastName: 'Vetrovs', count: 10, totalCount: 100 },
  { type: 'calling', firstName: 'Maria', lastName: 'Curtis', count: 3450, totalCount: 5000 },
  { type: 'calling', firstName: 'Aspen', lastName: 'Calzoni', count: 80, totalCount: 100 },
  { type: 'calling', firstName: 'Cristofer', lastName: 'Lipshutz', count: 32, totalCount: 100 },
  { type: 'calling', firstName: 'Davis', lastName: 'Vetrovs', count: 10, totalCount: 100 },
]

export const callsMock = [
  {
    type: 'calls',
    status: 'Désabonné',
    firstName: 'Carter',
    lastName: 'Septimus',
    genre: 'Homme',
    age: '19',
    author: 'Lincoln Kenter',
    updateTime: '23/08/2021 11:12 • 11 min',
  },
  {
    type: 'calls',
    status: 'Complété',
    firstName: 'Tatiana',
    lastName: 'Lubin',
    genre: 'Femme',
    age: '37',
    author: 'Jocelyn Vaccaro',
    updateTime: '23/08/2021 11:12 • 11 min',
  },
  {
    type: 'calls',
    status: 'Envoyé',
    firstName: 'Makenna',
    lastName: 'Herwitz',
    genre: 'Femme',
    age: '67',
    author: 'Abram Westervelt',
    updateTime: '23/08/2021 11:12 • 11 min',
  },
  {
    type: 'calls',
    status: 'Désabonné',
    firstName: 'Tatiana',
    lastName: 'Lubin',
    genre: 'Femme',
    age: '37',
    author: 'Jocelyn Vaccaro',
    updateTime: '23/08/2021 11:12 • 11 min',
  },
  {
    type: 'calls',
    status: 'Complété',
    firstName: 'Carter',
    lastName: 'Septimus',
    genre: 'Homme',
    age: '19',
    author: 'Lincoln Kenter',
    updateTime: '23/08/2021 11:12 • 11 min',
  },
  {
    type: 'calls',
    status: 'Envoyé',
    firstName: 'Tatiana',
    lastName: 'Lubin',
    genre: 'Femme',
    age: '37',
    author: 'Abram Westervelt',
    updateTime: '23/08/2021 11:12 • 11 min',
  },
  {
    type: 'calls',
    status: 'Désabonné',
    firstName: 'Makenna',
    lastName: 'Herwitz',
    genre: 'Femme',
    age: '67',
    author: 'Lincoln Kenter',
    updateTime: '23/08/2021 11:12 • 11 min',
  },
]

export const surveysMock = [
  { type: 'surveys', name: 'Cristofer Lipshutz', percent: '34' },
  { type: 'surveys', name: 'Zain Dokidis', percent: '24' },
  { type: 'surveys', name: 'Aspen Calzoni', percent: '18' },
  { type: 'surveys', name: 'Craig Culhane', percent: '17' },
  { type: 'surveys', name: 'Randy Carder', percent: '5' },
  { type: 'surveys', name: 'Maria Curtis', percent: '1' },
  { type: 'surveys', name: 'Cristofer Lipshutz', percent: '0' },
  { type: 'surveys', name: 'Randy Carder', percent: '98' },
  { type: 'surveys', name: 'Maren Donin', percent: '72' },
  { type: 'surveys', name: 'Maria Passaquindici', percent: '65' },
  { type: 'surveys', name: 'Jocelyn Dorwart', percent: '0' },
  { type: 'surveys', name: 'Randy Carder', percent: '5' },
  { type: 'surveys', name: 'Maria Curtis', percent: '1' },
  { type: 'surveys', name: 'Cristofer Lipshutz', percent: '0' },
  { type: 'surveys', name: 'Randy Carder', percent: '98' },
  { type: 'surveys', name: 'Maren Donin', percent: '72' },
  { type: 'surveys', name: 'Maria Passaquindici', percent: '65' },
  { type: 'surveys', name: 'Randy Carder', percent: '5' },
  { type: 'surveys', name: 'Maria Curtis', percent: '1' },
  { type: 'surveys', name: 'Cristofer Lipshutz', percent: '0' },
]
