export const mandates = {
  depute_europeen: 'Député européen',
  senateur: 'Sénateur',
  depute: 'Député',
  president_conseil_regional: 'Président du Conseil régional',
  conseiller_regional: 'Conseiller régional',
  president_conseil_departemental: 'Président du Conseil départemental',
  conseiller_departemental: 'Conseiller départemental',
  conseiller_territorial: 'Conseiller territorial',
  president_conseil_communautaire: 'Président du Conseil communautaire',
  conseiller_communautaire: 'Conseiller communautaire',
  maire: 'Maire',
  conseiller_municipal: 'Conseiller municipal',
  conseiller_arrondissement: "Conseiller d'arrondissement",
  membre_assemblee_fde: "Membre de l'Assemblée des Français de l'étranger",
  conseiller_fde: 'Conseiller FDE',
  delegue_consulaire: 'Délégué consulaire',
}

export const functions = {
  mayor: 'Maire',
  deputy_mayor: 'Maire délégué(e)',
  mayor_assistant: 'Adjoint(e) au maire',
  president_of_regional_council: 'Président(e) de conseil régional',
  vice_president_of_regional_council: 'Vice-président(e) de conseil régional',
  president_of_departmental_council: 'Président(e) de conseil départemental',
  vice_president_of_departmental_council: 'Vice-président(e) de conseil départemental',
  secretary: 'Secrétaire',
  quaestor: 'Questeur(rice)',
  president_of_national_assembly: "Président(e) de l'Assemblée nationale",
  vice_president_of_national_assembly: "Vice-président(e) de l'Assemblée nationale",
  president_of_senate: 'Président(e) du Sénat',
  vice_president_of_senate: 'Vice-président(e) du Sénat',
  president_of_commission: 'Président(e) de commission',
  president_of_group: 'Président(e) de groupe',
  president_of_epci: "Président(e) d'EPCI",
  vice_president_of_epci: "Vice-président(e) d'EPCI",
  deputy_vice_president_of_departmental_council: 'Vice-président(e) délégué du conseil départemental',
  other_member_of_standing_committee: 'Autre membre commission permanente',
  other_member: 'Autre membre',
}

export const supports = {
  invested: 'Investi',
  official: 'Soutient officiel',
  informal: 'Soutient informel',
  not_supported: 'Pas soutenu',
}

export const affiliations = [
  { key: 'RE', value: 'Renaissance' },
  { key: '-', value: '----', group: true },
  { key: 'AGR', value: 'Agir' },
  { key: 'ALLI', value: 'Alliance centriste' },
  { key: 'ANM', value: 'Animaliste' },
  { key: 'CPNT', value: 'Chasse pêche nature et traditions' },
  { key: 'DLF', value: 'Debout la France' },
  { key: 'DIV', value: 'Divers' },
  { key: 'DVC', value: 'Divers centre' },
  { key: 'DVD', value: 'Divers droite' },
  { key: 'DVG', value: 'Divers gauche' },
  { key: 'ECO', value: 'Ecologiste' },
  { key: 'VEC', value: 'Europe Ecologie-Les Verts' },
  { key: 'EXD', value: 'Extrême droite' },
  { key: 'EXG', value: 'Extrême gauche' },
  { key: 'FG', value: 'Front de gauche' },
  { key: 'FN', value: 'Front national' },
  { key: 'GJ', value: 'Gilets jaunes' },
  { key: 'GEN', value: 'Génération.s' },
  { key: 'FI', value: 'La France insoumise' },
  { key: 'REM', value: 'La République en Marche' },
  { key: 'LR', value: 'Les Républicains' },
  { key: 'LCR', value: 'Ligue communiste révolutionnaire' },
  { key: 'LO', value: 'Lutte ouvrière' },
  { key: 'MDM', value: 'Modem' },
  { key: 'MR', value: 'Mouvement radical / social-libéral' },
  { key: 'MDC', value: 'Mouvement des citoyens' },
  { key: 'MNR', value: 'Mouvement national républicain' },
  { key: 'NC', value: 'Nouveau Centre' },
  { key: 'COM', value: 'Parti communiste français' },
  { key: 'PG', value: 'Parti de gauche' },
  { key: 'SOC', value: 'Parti socialiste' },
  { key: 'PRG', value: 'Parti radical de gauche' },
  { key: 'PRV', value: 'Parti radical valoisien' },
  { key: 'RN', value: 'Rassemblement National' },
  { key: 'REG', value: 'Régionaliste' },
  { key: 'UD', value: 'Union de la droite' },
  { key: 'UG', value: 'Union de la gauche' },
  { key: 'UDI', value: 'Union des Démocrates et Indépendants' },
  { key: 'UC', value: 'Union du centre' },
  { key: 'UMP', value: 'Union pour un Mouvement populaire' },
  { key: 'UDF', value: 'Union pour la démocratie française' },
]
