const MAPBOX_TOKEN = process.env.REACT_APP_MAPBOX_TOKEN
const MAPBOX_STYLE = process.env.REACT_APP_MAPBOX_STYLE
const OAUTH_HOST = process.env.REACT_APP_OAUTH_HOST
const API_HOST = process.env.REACT_APP_API_HOST
const ADMIN_HOST = process.env.REACT_APP_ADMIN_HOST
const UNLAYER_PROJECT_ID = process.env.REACT_APP_UNLAYER_PROJECT_ID
const APP_VERSION = process.env.REACT_APP_VERSION
const APP_ENVIRONMENT = process.env.REACT_APP_ENVIRONMENT
const NODE_ENV = process.env.NODE_ENV
const OAUTH_CLIENT_ID = process.env.REACT_APP_OAUTH_CLIENT_ID
const INTERNAL_APP_ID = process.env.REACT_APP_INTERNAL_APP_ID
const SENTRY_DSN = process.env.REACT_APP_SENTRY_DSN

export {
  NODE_ENV,
  MAPBOX_TOKEN,
  MAPBOX_STYLE,
  OAUTH_HOST,
  API_HOST,
  ADMIN_HOST,
  UNLAYER_PROJECT_ID,
  APP_VERSION,
  APP_ENVIRONMENT,
  OAUTH_CLIENT_ID,
  INTERNAL_APP_ID,
  SENTRY_DSN,
}
