export const featuresLabels = {
  dashboard: 'Vue d’ensemble',
  contacts: 'Militants',
  messages: 'Messagerie',
  elections: 'Élections',
  ripostes: 'Action numérique',
  team: 'Groupes',
  news: 'Actualités',
  phoning_campaign: 'Phoning',
  pap: 'Porte à porte',
  pap_v2: 'Porte à porte local',
  survey: 'Questionnaires',
  my_team: 'Mon équipe',
  events: 'Évènements',
}

export default {
  dashboard: 'dashboard',
  contacts: 'contacts',
  messages: 'messages',
  elections: 'elections',
  ripostes: 'ripostes',
  team: 'team',
  news: 'news',
  phoning_campaign: 'phoning_campaign',
  pap: 'pap',
  pap_v2: 'pap_v2',
  survey: 'survey',
  my_team: 'my_team',
  events: 'events',
}
