export default {
  dashboard: 'Dashboard',
  contacts: 'Militants',
  messages: 'Messagerie',
  events: 'Evênements',
  my_team: 'Mon équipe',
  mobile_app: 'Application mobile',
  elections: 'Elections',
  pap: 'Porte à porte',
  ripostes: 'Ripostes',
  team: 'Groupes',
  news: 'Actualités',
  survey: 'Questionnaires',
  phoning_campaign: 'Phoning',
}
