export default {
  dashboard: '/',
  contacts: '/militants',
  messages: '/messagerie',
  elections: '/elections',
  ripostes: '/ripostes',
  team: '/groupes',
  news: '/actualites',
  phoning_campaign: '/phoning',
  pap: '/porte-a-porte',
  pap_v2: '/porte-a-porte-legislatives',
  survey: '/questionnaires',
  my_team: '/mon-equipe',
  events: '/evenements',
  department_site: '/site-departemental',
  elected_representative: '/registre-elus',
  adherent_formations: '/formations',
  general_meeting_reports: '/proces-verbal',
}

export const publicPaths = {
  signup: '/inscription',
  signupConfirm: '/inscription/felicitations',
  logout: '/deconnexion',
  auth: '/auth',
  ppd: '/politique-protection-donnees',
  cguWeb: '/mentions-legales-web',
  cguMobile: '/mentions-legales-mobile',
  cookiesWeb: '/utilisation-cookies-web',
  cookiesMobile: '/utilisation-cookies-mobile',
}
