export default {
  dashboard: '/',
  auth: '/auth',
  activists: '/militants',
  messagerie: '/messagerie',
  elections: '/elections',
  ripostes: '/ripostes',
  groups: '/groupes',
  news: '/actualites',
  phoning: '/phoning',
  DTD: '/porte-a-porte',
  signup: '/inscription',
  signupConfirm: '/inscription/felicitations',
  cgu: '/mentions-legales',
  ppd: '/politique-protection-donnees',
}
