export const roles = {
  general_secretary: 'Secrétaire général',
  treasurer: 'Trésorier',
  communication_manager: 'Responsable communication',
  mobilization_manager: 'Responsable mobilisation',
  new_members_manager: 'Responsable nouveaux adhérents',
  training_manager: 'Responsable formation',
  logistics_manager: 'Responsable logistique',
  procurations_manager: 'Responsable procurations',
  head_of_relations_and_training_of_elected_officials: 'Responsable des relations et formation élus',
  head_of_gender_equality: 'Responsable Égalité Femme / Homme',
  head_of_european_affairs: 'Responsable des questions européennes',
  compliance_and_finance_manager: 'Responsable conformité et finance',
  manager: 'Responsable',
}
