export enum FeatureEnum {
  ACTIONS = 'actions',
  ADHERENT_FORMATIONS = 'adherent_formations',
  COMMITTEE = 'committee',
  CONTACTS = 'contacts',
  CONTACTS_EXPORT = 'contacts_export',
  DASHBOARD = 'dashboard',
  DEPARTMENT_SITE = 'department_site',
  DESIGNATION = 'designation',
  DOCUMENTS = 'documents',
  ELECTED_REPRESENTATIVE = 'elected_representative',
  ELECTIONS = 'elections',
  EVENTS = 'events',
  GENERAL_MEETING_REPORTS = 'general_meeting_reports',
  MESSAGES = 'messages',
  PUBLICATIONS = 'publications',
  MY_TEAM = 'my_team',
  NEWS = 'news',
  PAP = 'pap',
  PAP_V2 = 'pap_v2',
  PHONING_CAMPAIGN = 'phoning_campaign',
  PROCURATIONS = 'procurations',
  REFERRALS = 'referrals',
  RIPOSTES = 'ripostes',
  STATUTORY_MESSAGE = 'statutory_message',
  SURVEY = 'survey',
  TEAM = 'team',
  FEATUREBASE = 'featurebase',
  RENTREE = 'rentree',
}

export const NewFeatures = [FeatureEnum.REFERRALS, FeatureEnum.RENTREE]
