export const fields = {
  title: 'title',
  zone: 'zone',
  goal: 'goal',
  endDate: 'endDate',
  brief: 'brief',
  team: 'team',
  survey: 'survey',
  gender: 'gender',
  firstName: 'firstName',
  lastName: 'lastName',
  ageMin: 'ageMin',
  ageMax: 'ageMax',
  adherentFromDate: 'adherentFromDate',
  adherentToDate: 'adherentToDate',
  zones: 'zones',
  certified: 'certified',
  committeeMember: 'committeeMember',
  emailSubscribed: 'emailSubscribed',
  SMSSubscribed: 'SMSSubscribed',
}
