export const paymentStatus = {
  pending_customer_approval: "En attente d'autorisation",
  pending_submission: "En attente d'envoi",
  submitted: 'En attente de traitement',
  confirmed: 'Paiement validé',
  paid_out: 'Reversé',
  cancelled: 'Annulé',
  customer_approval_denied: 'Autorisation refusée',
  failed: 'Échoué',
  charged_back: 'Remboursé',
  cheque_received: 'Chèque reçu',
  cheque_deposited: 'Chèque déposé',
  cheque_cashed: 'Chèque encaissé',
  cheque_rejected: 'Chèque refusé',
  disputed: 'Contesté',
}
